### ISSUE TITLE
Broken link to Multisig implementation

### ISSUE THREAD

**Issue by PaulRBerg** [hyperlane-xyz/docs#49]
Source:https://docs.hyperlane.xyz/docs/protocol/sovereign-consensus/multisig-ism

Broken link: https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/main/solidity/contracts/isms/MultisigIsm.sol

**Comment by tkporter** [comment]
@PaulRBerg thanks for flagging! fixed :)
